### ISSUE TITLE
Ease effect/ anticipation animation in the existing effects

### ISSUE THREAD

**Issue by aswinigh** [aswinigh/react-anim-text#2]
The existing animations should have an easing effect at each keyframe to add to the visual appeal.

**Comment by subhangi2731** [comment]
can you assign this issue to me @aswinigh

**Comment by aswinigh** [comment]
@subhangi2731 we are making some changes in the architecture. Join our [slack](https://join.slack.com/t/react-anim-text/shared_invite/zt-jztlgvow-jRmHaMc4P031VS7h6LTN0g) channel to discuss the changes.
